In [ ]:
import numpy as np

#Creat an array

In [ ]:
#a_arr = np.array(0,1,2,3) #WRONG
a_arr = np.array([0,1,2,3])
# or
a = [0,1,2,3]
a_arr = np.array(a)
print(a_arr)

[0 1 2 3]


Creat an array full of zeros

In [ ]:
a_arr = np.zeros((3,5))
print(a_arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Creat an array full of ones

In [ ]:
a_arr = np.ones((3,5))
print(a_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Creat an array full of random and depends on the state of the memory

In [ ]:
a_arr = np.empty((3,5),dtype= float)
print(a_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Create a vector between two numbers and by step

In [ ]:
a_arr = np.arange(10)
a_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a_arr = np.arange(10,22,2) # 0.5
a_arr

array([10, 12, 14, 16, 18, 20])

Create a vector between two numbers and by our number of partitions

In [ ]:
a_arr = np.linspace(10,22,5)
a_arr

array([10., 13., 16., 19., 22.])

Transpose a Vector

In [ ]:
a_arr = np.arange(10,22,2).reshape(-1,1)
a_arr

array([[10],
       [12],
       [14],
       [16],
       [18],
       [20]])

Create an array from a 1D vector

In [ ]:
a_arr = np.arange(10,22,2).reshape(2,3)
a_arr

array([[10, 12, 14],
       [16, 18, 20]])

In [ ]:
a_arr = np.linspace(10,22,8).reshape(2,2,2)
a_arr

array([[[10.        , 11.71428571],
        [13.42857143, 15.14285714]],

       [[16.85714286, 18.57142857],
        [20.28571429, 22.        ]]])

# Array Attributes

In [ ]:
#a = [1, 2, 3, 4]

a = [
    [0, 1],
     [0, 5]
     ]
"""
a = [
    [[0, 1, 1, 2], [1, 0, 0, 0],[0, 1, 1, 2]],
     [[2, 2, 3, 3], [6, 2, 1, 3],[1, 0, 0, 0]]
     ]
"""
print(type(a))

<class 'list'>


In [ ]:
a_arr = np.array(a)
print(type(a_arr))
print("Number of Dimentions: " ,a_arr.ndim)
print("Shape of the Array: " ,a_arr.shape)
print("Size of the Array: " ,a_arr.size)
print("Type of the Array: " ,a_arr.dtype)
print("item size (in bytes) of the Array: " ,a_arr.itemsize)
print("Buffer adress of the Array: " ,a_arr.data) # the buffer containing the actual elements
a_arr

<class 'numpy.ndarray'>
Number of Dimentions:  2
Shape of the Array:  (2, 2)
Size of the Array:  4
Type of the Array:  int64
item size (in bytes) of the Array:  8
Buffer adress of the Array:  <memory at 0x7fa0cc81bad0>


array([[0, 1],
       [0, 5]])

To save time we define a function to print Array's Attributes

In [ ]:
def print_att(np_array):
  print(type(a_arr))
  print("Number of Dimentions: " ,np_array.ndim)
  print("Shape of the Array: " ,np_array.shape)
  print("Size of the Array: " ,np_array.size)
  print("Type of the Array: " ,np_array.dtype)
  print("item size (in bytes) of the Array: " ,np_array.itemsize)
  print("Buffer adress of the Array: " ,np_array.data) # the buffer containing the actual elements


In [ ]:
a_arr = np.array(a,dtype="int32")
print_att(a_arr)
a_arr

<class 'numpy.ndarray'>
Number of Dimentions:  2
Shape of the Array:  (2, 2)
Size of the Array:  4
Type of the Array:  int32
item size (in bytes) of the Array:  4
Buffer adress of the Array:  <memory at 0x7fa0cc81bad0>


array([[0, 1],
       [0, 5]], dtype=int32)

In [ ]:
a_arr = np.array(a,dtype="float")
print_att(a_arr)
a_arr

<class 'numpy.ndarray'>
Number of Dimentions:  2
Shape of the Array:  (2, 2)
Size of the Array:  4
Type of the Array:  float64
item size (in bytes) of the Array:  8
Buffer adress of the Array:  <memory at 0x7fa0cc81bad0>


array([[0., 1.],
       [0., 5.]])

In [ ]:
a_arr = np.array(a,dtype="complex")
print_att(a_arr)
a_arr

<class 'numpy.ndarray'>
Number of Dimentions:  2
Shape of the Array:  (2, 2)
Size of the Array:  4
Type of the Array:  complex128
item size (in bytes) of the Array:  16
Buffer adress of the Array:  <memory at 0x7fa0cc61b1e0>


array([[0.+0.j, 1.+0.j],
       [0.+0.j, 5.+0.j]])

# Basic Operations

In [ ]:
a = np.array([1,2,3,0,4])
print("a =", a)
b = np.arange(5)
print("b =", b)
print("a+b= ",a+b)
print("a*b= ",a*b) # multiplying each element from a with the corresponding element from b
print("a@b= ",a@b) # dot product
print("a**2= ",a**2)
print("Cos(a*pi)= ",np.cos(a*np.pi/5))
print("True if a(i)>2 else False: \n", a>2)
print("a.sum()= ",a.sum())
print("a.max()= ",a.max())
print("a.min()= ",a.min())
print("sqrt(a)= ",np.sqrt(a))
print("exp(a)= ",np.exp(a))

a = [1 2 3 0 4]
b = [0 1 2 3 4]
a+b=  [1 3 5 3 8]
a*b=  [ 0  2  6  0 16]
a@b=  24
a**2=  [ 1  4  9  0 16]
Cos(a*pi)=  [ 0.80901699  0.30901699 -0.30901699  1.         -0.80901699]
True if a(i)>2 else False: 
 [False False  True False  True]
a.sum()=  10
a.max()=  4
a.min()=  0
sqrt(a)=  [1.         1.41421356 1.73205081 0.         2.        ]
exp(a)=  [ 2.71828183  7.3890561  20.08553692  1.         54.59815003]


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.linspace(2,8,4).reshape(2,2)
print("A= ",A)
print("B= ",B)
print("A@B= \n",A@B)
print("A.dot(B)= \n",A.dot(B))
print("A.sum()= ",A.sum(axis=0)) # sum of each column
print("A.max()= ",A.max(axis=0)) # max of each column
print("A.min()= ",A.min(axis=1)) # min of each row
print("\nA.cumsum()\n",A.cumsum(axis=1))  # cumulative sum along each row
print("\nvstack\n",np.vstack((A,B)))
print("\nhstack\n",np.hstack((A,B)))

A=  [[1 2]
 [3 4]]
B=  [[2. 4.]
 [6. 8.]]
A@B= 
 [[14. 20.]
 [30. 44.]]
A.dot(B)= 
 [[14. 20.]
 [30. 44.]]
A.sum()=  [4 6]
A.max()=  [3 4]
A.min()=  [1 3]

A.cumsum()
 [[1 3]
 [3 7]]

vstack
 [[1. 2.]
 [3. 4.]
 [2. 4.]
 [6. 8.]]

hstack
 [[1. 2. 2. 4.]
 [3. 4. 6. 8.]]


In [ ]:
rg = np.random.default_rng(seed= 1) # create instance of default random number generator
a = rg.random((2,3))
print("Random Matrix: ", a)
print("Element type name: ",a.dtype.name)

Random Matrix:  [[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]
Element type name:  float64


In [ ]:
def f(x,y):
  return 5*x+y

b = np.fromfunction(f,(5,4))
print(b)
print(b.ravel()) # returns the array, flattened

[[ 0.  1.  2.  3.]
 [ 5.  6.  7.  8.]
 [10. 11. 12. 13.]
 [15. 16. 17. 18.]
 [20. 21. 22. 23.]]
[ 0.  1.  2.  3.  5.  6.  7.  8. 10. 11. 12. 13. 15. 16. 17. 18. 20. 21.
 22. 23.]


By: Eng. Alaa Alnissany