[**scipy**](https://docs.scipy.org/doc/scipy/tutorial/linalg.html)

In [1]:
import numpy as np
from scipy import linalg

In [2]:
A = np.array([[1,2],[3,4]])
print("A:\n",A)
print("inv(A):\n",linalg.inv(A))
print("Transpose(A):\n",A.T)

A:
 [[1 2]
 [3 4]]
inv(A):
 [[-2.   1. ]
 [ 1.5 -0.5]]
Transpose(A):
 [[1 3]
 [2 4]]


# Finding the inverse

In [3]:
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
B = linalg.inv(A)
I = A@B
print(A)
print(B)
print(I)

[[1 3 5]
 [2 5 1]
 [2 3 8]]
[[-1.48  0.36  0.88]
 [ 0.56  0.08 -0.36]
 [ 0.16 -0.12  0.04]]
[[ 1.00000000e+00 -1.11022302e-16  4.85722573e-17]
 [ 3.05311332e-16  1.00000000e+00  7.63278329e-17]
 [ 2.22044605e-16 -1.11022302e-16  1.00000000e+00]]


# Solving a linear system

In [4]:
#A*x=b
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
b = np.array([[10,8,3]])
x = linalg.inv(A)@b.T # Slow
print(x)
print(A@x-b.T)
x = np.linalg.solve(A,b.T) # Fast
print(x)
print(A.dot(x)-b.T)

[[-9.28]
 [ 5.16]
 [ 0.76]]
[[ 0.00000000e+00]
 [-1.77635684e-15]
 [-8.88178420e-16]]
[[-9.28]
 [ 5.16]
 [ 0.76]]
[[ 0.00000000e+00]
 [-1.77635684e-15]
 [-1.77635684e-15]]


# Finding the determinant

In [7]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [6]:
linalg.det(A)

-2.0

# **Decompositions**


# Eigenvalues and eigenvectors

In [8]:
la, v = linalg.eig(A)
l1, l2 = la
print(l1, l2)   # eigenvalues
print(v[:, 0])   # first eigenvector
print(v[:, 1])   # second eigenvector
print(np.sum(abs(v**2), axis=0))  # eigenvectors are unitary
v1 = np.array(v[:, 0]).T
print(linalg.norm(A.dot(v1) - l1*v1))  # check the computation

(-0.3722813232690143+0j) (5.372281323269014+0j)
[-0.82456484  0.56576746]
[-0.41597356 -0.90937671]
[1. 1.]
5.551115123125783e-17


# Singular value decomposition

In [18]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
M,N = A.shape
U,s,Vh = linalg.svd(A)
Sig = linalg.diagsvd(s,M,N)
U

array([[-0.3863177 , -0.92236578],
       [-0.92236578,  0.3863177 ]])

In [20]:
Sig

array([[9.508032  , 0.        , 0.        ],
       [0.        , 0.77286964, 0.        ]])

In [21]:
Vh

array([[-0.42866713, -0.56630692, -0.7039467 ],
       [ 0.80596391,  0.11238241, -0.58119908],
       [ 0.40824829, -0.81649658,  0.40824829]])

In [22]:
U.dot(Sig.dot(Vh)) #check computation

array([[1., 2., 3.],
       [4., 5., 6.]])

By: Eng. Alaa Alnissany